version: '3.8'

services:
  ideas-app:
    build: .
    container_name: ideas-webapp
    ports:
      - "3000:3000"
    volumes:
      - ideas-data:/app/data
      - ideas-uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/ideas.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/ideas', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ideas-data:
    driver: local
  ideas-uploads:
    driver: local

